omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
omp_place = cores(1) / omp_num_threads = 1,1
